---
- name: create a data directory for consul
  file: path=/srv/consul state=directory

- name: install docker-compose.yml
  template: src=docker-compose.yml dest=/root/docker-compose.yml

- name: create consul config directory
  file: path=/root/config state=directory

- name: install custom consul Dockerfile
  copy: src=Dockerfile dest=/root/Dockerfile

- name: install consul config
  template: src=consul.json.j2 dest=/root/config/consul.json

- name: stop docker containers
  command: docker-compose stop

- name: remove docker containers
  command: docker-compose rm -f

- name: pull docker images
  command: docker-compose pull

- name: build docker images
  command: docker-compose build

- name: run docker compose
  command: docker-compose up -d consul
