consul:
  build: /srv/consul
  hostname: "{{ inventory_hostname }}"
  restart: always
  net: host
  volumes:
    - /root/.docker:/root/.docker
    - /srv/consul:/consul/data
    - /root/consul/config:/consul/config
  command: >
    agent
    "-advertise={{ private_ip }}"
    "-retry-join={{ jupyterhub_host }}"
    -disable-host-node-id=true

swarm:
  image: swarm:1.2.8
  restart: always
  volumes:
    - /root/.docker:/root/.docker
  command: >
    join
    "--addr={{ private_ip }}:2375"
    --discovery-opt kv.cacertfile=/root/.docker/ca.pem
    --discovery-opt kv.certfile=/root/.docker/cert.pem
    --discovery-opt kv.keyfile=/root/.docker/key.pem
    "consul://{{ jupyterhub_host }}:8501/swarm"
